name: unself_preview
description: A common util for Widgetbooks and preview

publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  widgetbook: ^2.4.1
  widgetbook_generator: ^2.4.1
  widgetbook_annotation: ^2.1.0
  device_frame: ^1.1.0

  source_gen:
  build:

  unself_style:
  unself_component:

dev_dependencies:
  # Code Analysis

  unself_analysis:

  # Code Generation

  build_runner: ^2.3.0
  freezed: ^2.2.0
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
