builders:
  theme_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["themeBuilder"]
    build_extensions: { ".dart": [".theme.widgetbook.json"] }
    auto_apply: dependents
    runs_before: [":unself_preview"]
    build_to: cache
  locales_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["localesBuilder"]
    build_extensions: { ".dart": [".locales.widgetbook.json"] }
    auto_apply: dependents
    runs_before: [":unself_preview"]
    build_to: cache
  localization_delegates_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["localizationDelegatesBuilder"]
    build_extensions: { ".dart": [".delegates.widgetbook.json"] }
    auto_apply: dependents
    runs_before: [":unself_preview"]
    build_to: cache
  story_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["storyBuilder"]
    build_extensions: { ".dart": [".usecase.widgetbook.json"] }
    auto_apply: dependents
    runs_before: [":unself_preview"]
    build_to: cache
  devices_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["devicesBuilder"]
    build_extensions: { ".dart": [".devices.widgetbook.json"] }
    auto_apply: dependents
    runs_before: [":unself_preview"]
    build_to: cache
  text_scale_factor_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["textScaleFactorsBuilder"]
    build_extensions: { ".dart": [".textscalefactors.widgetbook.json"] }
    auto_apply: dependents
    runs_before: [":unself_preview"]
    build_to: cache
  device_frame_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["deviceFrameBuilder"]
    build_extensions: { ".dart": [".deviceframebuilder.widgetbook.json"] }
    auto_apply: dependents
    runs_before: [":unself_preview"]
    build_to: cache
  localization_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["localizationBuilder"]
    build_extensions: { ".dart": [".localizationbuilder.widgetbook.json"] }
    auto_apply: dependents
    runs_before: [":unself_preview"]
    build_to: cache
  app_resolver_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["appResolverBuilder"]
    build_extensions: { ".dart": [".appbuilder.widgetbook.json"] }
    auto_apply: dependents
    runs_before: [":unself_preview"]
    build_to: cache
  scaffold_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["scaffoldBuilder"]
    build_extensions: { ".dart": [".scaffoldbuilder.widgetbook.json"] }
    auto_apply: dependents
    runs_before: [":unself_preview"]
    build_to: cache
  theme_resolver_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["themeResolverBuilder"]
    build_extensions: { ".dart": [".themebuilder.widgetbook.json"] }
    auto_apply: dependents
    runs_before: [":unself_preview"]
    build_to: cache
  use_case_builder:
    import: "package:widgetbook_generator/builder.dart"
    builder_factories: ["useCaseBuilder"]
    build_extensions: { ".dart": [".usecasebuilder.widgetbook.json"] }
    auto_apply: dependents
    runs_before: [":unself_preview"]
    build_to: cache
  unself_preview:
    import: "package:unself_preview/src/builder.dart"
    builder_factories: ["previewBuilder"]
    build_extensions: { ".dart": [".preview.dart"] }
    auto_apply: dependents
    build_to: source

targets:
  $default:
    builders:
      widgetbook_generator:
        enabled: false
        # Disable to use customized builder (with ignore_for_file)
