name: unself_monitoring_service
description: Provides analytics, error reporting, and performance monitoring services.

version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  rudder_sdk_flutter: ^2.2.0
  rudder_integration_firebase_flutter: ^1.0.1

  firebase_core: ^2.4.0
  firebase_analytics: ^10.0.7
  firebase_crashlytics: ^3.0.7
  firebase_performance: ^0.9.0+7
  firebase_app_check: ^0.1.1+6

  sentry: ^6.18.1
  sentry_flutter: ^6.18.1

  package_info_plus: ^3.0.2

dev_dependencies:

  # Code Analysis

  unself_analysis: 
  
  # Testing

  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^9.1.0 
  mocktail: ^0.3.0 