name: unself_script
description: Scripts for unself mono-repo.

version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  args: ^2.3.1
  glob: ^2.1.1

dev_dependencies:
  # Code Quality

  unself_analysis:
  dart_code_metrics: ^5.4.0
  dependency_validator: ^3.2.2
