name: unself_model
description: Domain model for unself project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.2.0

dev_dependencies:
  # Code Analysis

  unself_analysis:

  # Code Generation

  build_runner: ^2.3.0
  freezed: ^2.2.0
  json_serializable: ^6.5.4

  # Testing

  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^0.3.0
