name: unself_user
description: User generated content and config repository for unself app.

publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  unself_model:

  freezed_annotation: ^2.1.0

dev_dependencies:
  # Code Quality

  unself_analysis:
  dart_code_metrics: ^5.4.0
  dependency_validator: ^3.2.2

  # Code Generation

  build_runner: ^2.3.0
  freezed: ^2.2.0
  json_serializable: ^6.5.4

  # Testing

  flutter_test:
    sdk: flutter

  # bloc_test: ^9.1.0
  # mocktail: ^0.3.0
