name: unself_unpack
description: Unpack archive data service for Unself project.

publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  unself_local_database:
  unself_model:

  archive: ^3.3.0

dev_dependencies:
  # Code Quality

  unself_analysis:
  dart_code_metrics: ^5.4.0
  dependency_validator: ^3.2.2

  # Testing

  flutter_test:
    sdk: flutter

  # bloc_test: ^9.1.0
  # mocktail: ^0.3.0
