name: un_settings_appearance
description: Appearance Settings Page for unself app.

publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.1.0

  un_style:
  un_ui:

  un_monitoring:
  un_user_repository:

  un_model:

dev_dependencies:
  # Code Quality

  un_analysis:
  dart_code_metrics: ^4.19.2
  dependency_validator: ^3.2.2

  # Code Generation

  build_runner: ^2.3.0
  freezed: ^2.2.0
  json_serializable: ^6.5.4

  # Testing

  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.0
  # mocktail: ^0.3.0

  provider: ^6.0.5
