name: un_database
description: SQLite Database for unself app.

publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  drift: ^2.6.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.2

  slugid: ^1.1.1

dev_dependencies:
  # Code Quality

  un_analysis:
  dart_code_metrics: any
  dependency_validator: ^3.2.2

  # Code Generation

  build_runner: ^2.3.0
  drift_dev: ^2.6.0

  # Testing

  flutter_test:
    sdk: flutter

  # bloc_test: ^9.1.0
  # mocktail: ^0.3.0

  provider: ^6.0.5
