name: unself_database
description: SQLite Database

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  drift: ^2.4.2
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.2

  unself_model:

dev_dependencies:
  flutter_test:
    sdk: flutter
  # mocktail: ^0.3.0
  unself_analysis:

  drift_dev: ^2.4.1
  build_runner: ^2.0.3
  