targets:
  $default:
    builders:
      freezed:freezed:
        generate_for:
          - lib/src/logic/*.dart
      json_serializable:json_serializable:
        generate_for:
          - lib/src/logic/*.dart
