name: unself_app
description: Flutter app for Unself project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^6.0.1
  provider: ^6.0.5

  unself_database:
  unself_license:
  unself_monitoring:
  unself_user:

  unself_component:
  unself_style:

dev_dependencies:
  # Code Generation

  build_runner: ^2.3.0
  go_router_builder: ^1.0.15

  # Testing

  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^0.3.0

  unself_analysis:

flutter:
  uses-material-design: true
