name: unself_app
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  unself_monitoring_service:
  unself_license_repository:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  unself_analysis:

flutter:
  uses-material-design: true
