name: unself_{{package_name.snakeCase()}}
description: {{package_description}}

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  # mocktail: ^0.3.0 
  unself_analysis: