name: unself_license_repository
description: License and attribution repository for unself app.

version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  # Code Analysis

  unself_analysis:

  # Testing

  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
