name: unself_analysis
description: Analysis options for all packages under this mono-repo.

version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter_lints: ^2.0.1