name: unself_analysis
description: Analysis options for unself mono-repo.

version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter_lints: ^2.0.1
  very_good_analysis: ^3.1.0

dev_dependencies:
  # Code Quality

  dart_code_metrics: ^5.4.0
  dependency_validator: ^3.2.2
