name: CI for Dev Environment

on:
  push:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hygiene:
    uses: thipokch/unself/.github/workflows/ci-hygiene.yaml@master
    secrets: inherit
    with:
      env: dev
  build:
    uses: thipokch/unself/.github/workflows/ci-build.yaml@master
    needs: hygiene
    secrets: inherit
    with:
      env: dev
      build_num: ${{ needs.hygiene.outputs.build_num }}
  deploy:
    uses: thipokch/unself/.github/workflows/ci-deploy.yaml@master
    # needs: [hygiene, build, release]
    needs: [hygiene, build]
    secrets: inherit
    permissions:
      contents: write
    with:
      env: dev
      build_num: ${{ needs.hygiene.outputs.build_num }}
      # releases_created: ${{ needs.release.outputs.releases_created }}
      # changelog: ${{ needs.release.outputs.changelog }}

  # doc:
  #   uses: thipokch/unself/.github/workflows/docs.yaml@master
